# Generated by Django 5.2.8 on 2025-11-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_favorito_precio_minimo_deseado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='container_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clase del Contenedor'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='container_tag',
            field=models.CharField(blank=True, default='div', max_length=50, verbose_name='Tag del Contenedor (ej: div, article)'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='imagen_selector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Selector Imagen (CSS)'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='precio_selector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Selector Precio (CSS)'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='titulo_selector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Selector Título (CSS)'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='url_busqueda',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Búsqueda/Categoría'),
        ),
    ]
